[package]
authors = ["Wu Young <doomsplayer@gmail.com>"]
name = "nextaction-rs"
version = "0.1.0"

[dependencies]
hyper = "0.9.10"
serde = "0.8.0"
serde_json = "0.8.0"
serde_macros = "0.8.0"
wrapped_enum = "0.1.3"
log = "0.3.6"
env_logger = "0.3.4"
url = "1.1.1"
mime = "0.2.1"
json = "0.10.0"
uuid = { version = "0.2.3", features = ["serde", "v4"] }

[lib]
name = "nextaction"
